### ISSUE TITLE
Chrome app

### ISSUE THREAD

**Issue by mirzadelic** [realtime-framework/ChromePushNotifications#2]
Can i use this code on chrome app or extension?
App runs local index.html file.

**Comment by realtime-framework** [comment]
I guess it's not possible directly due to the HTTPS restriction.

However you can connect directly to GCM from your extension. Maybe this guide from Goggle Cloud Messaging can help:
https://developers.google.com/cloud-messaging/chrome/client#project-setup

**Comment by mirzadelic** [comment]
I use GCM, does realtime use GCM in background, when i send from realtime will i receive in GCM?

**Comment by realtime-framework** [comment]
Yes, we'll relay Realtime messages to GCM if you setup the GCM push notifications for your Realtime appkey (http://messaging-public.realtime.co/documentation/starting-guide/mobilePushGCM.html) and your client subscribes the channel with notifications (see https://github.com/realtime-framework/ChromePushNotifications/blob/94d0bceb86788ea15e5a13402672f043cac3a55c/index.js#L42)
